language: cpp

compiler:
     - gcc

addons:
    apt:
        sources: ubuntu-toolchain-r-test
        packages: [libfftw3-dev]

script:
     - mkdir -p build
     - cd build
     - cmake .. 
     - make
     - make test
