language: cpp

compiler:
     - gcc

addons:
    apt:
        sources: ubuntu-toolchain-r-test
        packages:
            - gcc-7
            - g++-7
            - libfftw3-dev
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz

script:
     - mkdir updates
     - wget https://cmake.org/files/v3.12/cmake-3.12.0-Linux-x86_64.sh
     - sh cmake-3.12.0-Linux-x86_64.sh --prefix=updates --exclude-subdir
     - export PATH=`pwd`/updates/bin:$PATH
     - export CC=gcc-7
     - export CXX=g++-7
     - mkdir -p build
     - cd build
     - cmake --version
     - cmake -DCMAKE_RULE_MESSAGES:BOOL=OFF -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON ..
     - make
     - make test
